// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CameraController from "./camera_controller"
application.register("camera", CameraController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PhotoPreviewController from "./photo_preview_controller"
application.register("photo-preview", PhotoPreviewController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import TogglePasswordController from "./toggle_password_controller"
application.register("toggle-password", TogglePasswordController)

import AccentCorrectorController from "./accent_corrector_controller"
application.register("accent-corrector", AccentCorrectorController)
