default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: stock_control
  password: password

development:
  <<: *default
  database: stock_control_development

test:
  <<: *default
  database: stock_control_test

production:
  <<: *default
  database: stock_control_production
